#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
  CREATE DATABASE test;
  CREATE USER ${SQL_USERNAME} WITH ENCRYPTED PASSWORD '${SQL_PASSWORD}';
  GRANT ALL PRIVILEGES ON DATABASE ${SQL_USERNAME} TO ${SQL_USERNAME};
EOSQL